import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const theme = "light";

  // await cookies()
  //   .then((cookies) => {
  //     const value = cookies.get("theme")?.value;
  //     if (typeof value === "string") theme = value;
  //   })
  //   .catch();

  return (
    <html lang="he" dir="rtl" data-theme="light">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml"></link>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header /> */}
        <p>
          {new Date().toLocaleTimeString("he-IL", {
            timeZone: "Asia/Jerusalem",
            hour12: false, // לפורמט של 24 שעות
            hour: "2-digit",
            minute: "2-digit",
            second: "2-digit",
          })}
        </p>
        {children}
      </body>
    </html>
  );
}
